services:
  - type: web
    name: tabbycat
    env: python
    plan: free
    region: oregon
    buildCommand: "./bin/render_compile.sh"
    startCommand: "npm run serve-render"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tc_db
          property: connectionString
      - key: REDIS_HOST
        fromService:
          type: redis
          name: tc_redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: tc_redis
          property: port
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: TAB_DIRECTOR_EMAIL
        sync: false
      - key: TIME_ZONE
        sync: false
  - type: redis
    name: tc_redis
    ipAllowList: # required
      - source: 0.0.0.0
        description: everywhere
    plan: free
    maxmemoryPolicy: allkeys-lru # (default)

databases:
  - name: tc_db
    databaseName: tabbycat
    user: tabbycat
    plan: free
